### ISSUE TITLE
Error when configuring multiple hurricane dns host records

### ISSUE THREAD

**Issue by HEMO74** [alexzorin/certbot-dns-multi#5]
1. Content of dns-multi.ini:
  _dns_multi_provider=hurricane
  HURRICANE_TOKENS=host1.domain:token1, host2.domain:token2, host3.domain:token3_
Result of running _docker run --rm -it -v /etc/letsencrypt:/etc/letsencrypt ghcr.io/alexzorin/certbot-dns-multi certonly -a dns-multi --dry-run --dns-multi-credentials /etc/letsencrypt/dns-multi.ini -d host1.domain -vvvv_ is error:

Calling registered functions
Cleaning up challenges
Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/opt/certbot/lib/python3.9/site-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/lib/python3.9/site-packages/certbot/_internal/main.py", line 1864, in main
    return config.func(config, plugins)
  File "/opt/certbot/lib/python3.9/site-packages/certbot/_internal/main.py", line 1597, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/lib/python3.9/site-packages/certbot/_internal/main.py", line 129, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/opt/certbot/lib/python3.9/site-packages/certbot/_internal/renewal.py", line 395, in renew_cert
    new_cert, new_chain, new_key, _ = le_client.obtain_certificate(domains, new_key)
  File "/opt/certbot/lib/python3.9/site-packages/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/lib/python3.9/site-packages/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
  File "/opt/certbot/lib/python3.9/site-packages/certbot/_internal/auth_handler.py", line 88, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/opt/certbot/lib/python3.9/site-packages/certbot_dns_multi/_internal/dns_multi.py", line 80, in perform
    self._setup_credentials()
  File "/opt/certbot/lib/python3.9/site-packages/certbot_dns_multi/_internal/dns_multi.py", line 71, in _setup_credentials
    LegoClient.configure(provider, lego_environ)
  File "/opt/certbot/lib/python3.9/site-packages/certbot_dns_multi/_internal/dns_multi.py", line 147, in configure
    LegoClient._raise_for_response(
  File "/opt/certbot/lib/python3.9/site-packages/certbot_dns_multi/_internal/dns_multi.py", line 193, in _raise_for_response
    raise errors.PluginError(resp["error"])
certbot.errors.PluginError: unknown command

2. With single record in dns-multi.ini:
  _dns_multi_provider=hurricane
  HURRICANE_TOKENS=host1.domain:token1_
all OK.

**Comment by alexzorin** [comment]
That's a fascinating bug.

What's happening is that the `configobj` ini parsing library is deserializing the `ini` file as a list:

    "HURRICANE_TOKENS": ["host1.domain:token1", "host2.domain:token2", "host3.domain:token"]

whereas the plugin expects `HURRICANE_TOKENS` to be a simple string.

What you can do is enclose the value in double quotes:

    HURRICANE_TOKENS="host1.domain:token1, host2.domain:token2, host3.domain:token3"

I've updated the README so that the example uses quoting.

Hope that helps!
