### ISSUE TITLE
not working with alpine/musl

### ISSUE THREAD

**Issue by Zoey2936** [alexzorin/certbot-dns-multi#8]
Dockerfile:
```Dockerfile
FROM python:3.12.0-alpine3.18
ENV PATH="/usr/local/certbot/bin:$PATH"
RUN apk add --no-cache ca-certificates build-base libffi-dev go && \
    python3 -m venv /usr/local/certbot && \
    pip install --no-cache-dir \
                               certbot==2.7.3 \
                               certbot-dns-multi==4.14.2
```

```console
/ # certbot
The 'certbot_dns_multi._internal.dns_multi' plugin errored while loading: Error relocating /usr/local/certbot/lib/python3.12/site-packages/lego_bridge.cpython-312-x86_64-linux-musl.so: free: initial-exec TLS resolves to dynamic definition in /usr/local/certbot/lib/python3.12/site-packages/lego_bridge.cpython-312-x86_64-linux-musl.so. You may need to remove or update this plugin. The Certbot log will contain the full error details and this should be reported to the plugin developer.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/certbot-log-ob9qr7js/log or re-run Certbot with -v for more details.
/ # cat /tmp/certbot-log-ob9qr7js/log
2023-10-26 09:20:50,975:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/certbot/lib/python3.12/site-packages/certbot/_internal/plugins/disco.py", line 191, in find_all
    cls._load_entry_point(entry_point, plugins)
  File "/usr/local/certbot/lib/python3.12/site-packages/certbot/_internal/plugins/disco.py", line 203, in _load_entry_point
    plugin_ep = PluginEntryPoint(entry_point)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/certbot/lib/python3.12/site-packages/certbot/_internal/plugins/disco.py", line 42, in __init__
    self.plugin_cls: Type[interfaces.Plugin] = entry_point.load()
                                               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/local/certbot/lib/python3.12/site-packages/certbot_dns_multi/_internal/dns_multi.py", line 11, in <module>
    from lego_bridge import cmd
ImportError: Error relocating /usr/local/certbot/lib/python3.12/site-packages/lego_bridge.cpython-312-x86_64-linux-musl.so: free: initial-exec TLS resolves to dynamic definition in /usr/local/certbot/lib/python3.12/site-packages/lego_bridge.cpython-312-x86_64-linux-musl.so

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/certbot/bin/certbot", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/certbot/lib/python3.12/site-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/certbot/lib/python3.12/site-packages/certbot/_internal/main.py", line 1841, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/certbot/lib/python3.12/site-packages/certbot/_internal/plugins/disco.py", line 193, in find_all
    raise errors.PluginError(
certbot.errors.PluginError: The 'certbot_dns_multi._internal.dns_multi' plugin errored while loading: Error relocating /usr/local/certbot/lib/python3.12/site-packages/lego_bridge.cpython-312-x86_64-linux-musl.so: free: initial-exec TLS resolves to dynamic definition in /usr/local/certbot/lib/python3.12/site-packages/lego_bridge.cpython-312-x86_64-linux-musl.so. You may need to remove or update this plugin. The Certbot log will contain the full error details and this should be reported to the plugin developer.
2023-10-26 09:20:50,975:ERROR:certbot._internal.log:The 'certbot_dns_multi._internal.dns_multi' plugin errored while loading: Error relocating /usr/local/certbot/lib/python3.12/site-packages/lego_bridge.cpython-312-x86_64-linux-musl.so: free: initial-exec TLS resolves to dynamic definition in /usr/local/certbot/lib/python3.12/site-packages/lego_bridge.cpython-312-x86_64-linux-musl.so. You may need to remove or update this plugin. The Certbot log will contain the full error details and this should be reported to the plugin developer.
/ # ldd /usr/local/certbot/lib/python3.12/site-packages/lego_bridge.cpython-312-x86_64-linux-musl.so
        /lib/ld-musl-x86_64.so.1 (0x7f3192a30000)
        libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f3192a30000)
Error relocating /usr/local/certbot/lib/python3.12/site-packages/lego_bridge.cpython-312-x86_64-linux-musl.so: PyUnicode_FromString: symbol not found
Error relocating /usr/local/certbot/lib/python3.12/site-packages/lego_bridge.cpython-312-x86_64-linux-musl.so: PyBytes_AsString: symbol not found
Error relocating /usr/local/certbot/lib/python3.12/site-packages/lego_bridge.cpython-312-x86_64-linux-musl.so: Py_DecRef: symbol not found
Error relocating /usr/local/certbot/lib/python3.12/site-packages/lego_bridge.cpython-312-x86_64-linux-musl.so: PyModule_Create2: symbol not found
Error relocating /usr/local/certbot/lib/python3.12/site-packages/lego_bridge.cpython-312-x86_64-linux-musl.so: PyUnicode_AsUTF8String: symbol not found
Error relocating /usr/local/certbot/lib/python3.12/site-packages/lego_bridge.cpython-312-x86_64-linux-musl.so: PyArg_ParseTuple: symbol not found
```

**Comment by alexzorin** [comment]
Yeah, linking against musl doesn't work, sorry. That's the reason why the Docker container pulls in an image with glibc. I don't really know what would be involved in making it compatible and I don't have time to look into it myself.
